workspace = { members = ["src/struct_test"] }
[package]
name = "test_app0001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.34"
webbrowser = "0.8.13"
